package sg.edu.iss.asdadt8.review;

public enum BadKeyWords 
{
	terrible, a55, anal, anus, ar5e, arrse, arse, ass, asses, assfucker, assfukka, asshole, assholes, asswhole, a_s_s, b00bs, b17ch, b1tch, ballbag, 
	balls, ballsack, bastard, beastial, beastiality, bellend, bestial, bestiality, biatch, bitch, bitcher, bitchers, bitches, bitchin, 
	bitching, bloody, blowjob, blowjobs, boiolas, bollock, bollok, boob, boobs, booobs, boooobs, booooobs, booooooobs, breasts, buceta,
	bugger, bum, butt, butthole, buttmuch, buttplug, c0ck, c0cksucker, cawk, chink, cipa, cl1t, clit, clitoris, clits, cnut, cockface, 
	cockhead, cockmunch, cockmuncher, cocks, cocksuck, cocksucked, cocksucker, cocksucking, cocksucks, cocksuka, cocksukka, cok, cokmuncher,
	coksucka, coon, cox, crap, cum, cummer, cumming, cums, cumshot, cunilingus, cunillingus, cunnilingus, cunt, cuntlick, cuntlicker, 
	cuntlicking, cunts, cyalis, cyberfuc, cyberfuck, cyberfucked, cyberfucker, cyberfuckers, cyberfucking, d1ck, dick, dickhead, dildo, 
	dildos, dink, dinks, dirsa, dlck, doggin, dogging, donkeyribber, doosh, duche, dyke, ejaculate, ejaculated, ejaculates, ejaculating, 
	ejaculatings, ejaculation, ejakulate, f4nny, fag, fagging, faggitt, faggot, faggs, fagot, fagots, fags, fanny, fannyflaps, fannyfucker, 
	fanyy, fatass, fcuk, fcuker, fcuking, feck, fecker, felching, fellate, fellatio, fingerfuck, fingerfucked, fingerfucker, fingerfuckers, 
	fingerfucking, fingerfucks, fistfuck, fistfucked, fistfucker, fistfuckers, fistfucking, fistfuckings, fistfucks, flange, fook, fooker, 
	fucka, fucked, fuckers, fuckhead, fuckheads, fuckin, fucking, fuckings, fuckingshitmotherfucker, fuckme, fucks, fuckwhit, fuckwit, 
	fudgepacker, fuk, fuker, fukker, fukkin, fuks, fukwhit, fukwit, fux, fux0r, f_u_c_k, gangbang, gangbanged, gangbangs, gaylord, gaysex,
	goatse, goddamn, goddamned, hardcoresex, hell, heshe, hoar, hoare, hoer, homo, hore, horniest, horny, hotsex, jackoff, jap, jism, jiz,
	jizm, jizz, kawk, knob, knobead, knobed, knobend, knobhead, knobjocky, knobjokey, kock, kondum, kondums, kum, kummer, kumming, kums, 
	kunilingus, l3itch, labia, lmfao, lust, lusting, m0f0, m0fo, m45terbate, ma5terb8, ma5terbate, masochist,masterb8, masterbat, masterbat3,
	masterbate, masterbation, masterbations, masturbate, mof0, mofo, mothafuck, mothafucka, mothafuckas, mothafuckaz, mothafucked, 
	mothafucker, mothafuckers, mothafuckin, mothafucking, mothafuckings, mothafucks, motherfuck, motherfucked, motherfucker, motherfuckers,
	motherfuckin, motherfucking, motherfuckings, motherfuckka, motherfucks, muff, mutha, muthafecker, muthafuckker, muther, mutherfucker, 
	n1gga, n1gger, nazi, nigg3r, nigg4h, nigga, niggah, niggas, niggaz, nigger, niggers, nob, nobhead, nobjocky, nobjokey, numbnuts, 
	nutsack, orgasim, orgasims, orgasm, orgasms, p0rn, pawn, pecker, penis, penisfucker, phonesex, phuck, phuk, phuked, phuking, phukked, 
	phukking, phuks, phuq, pigfucker, pimpis, piss, pissed, pisser, pissers, pisses, pissflaps, pissin, pissing, pissoff, porn, porno, 
	pornography, pornos, prick, pricks, pron, pube, pusse, pussi, pussies, pussys, rectum, retard, rimjaw, rimming, sadist, schlong, screwing,
	scroat, scrote, scrotum, semen, sh1t, shag, shagger, shaggin, shagging, shemale, shitdick, shite, shited, shitey, shitfuck, shitfull, 
	shithead, shiting, shitings, shits, shitted, shitter, shitters, shitting, shittings, shitty, skank, slut, sluts, smegma, smut, snatch, 
	spac, spunk, s_h_i_t, t1tt1e5, t1tties, teets, teez, testical, testicle, tit, titfuck, titt, tittie5, tittiefucker, titties, tittyfuck, 
	tittywank, titwank, tosser, turd, tw4t, twat, twathead, twatty, twunt, twunter, v14gra, v1gra, vagina, viagra, vulva, w00se, wang, wank,
	wanker, wanky, whoar, whore, willies, willy, xrated, xxx, arsehole, assbag, assbandit, assbanger, assbite, assclown, asscock, asscracker,
	assface, assfuck, assgoblin, asshat, asshead, asshopper, assjacker, asslick, asslicker, assmonkey, assmunch, assmuncher, assnigger, 
	asspirate, assshit, assshole, asssucker, asswad, asswipe, axwound, bampot, beaner, bitchass, bitchtits, bitchy, bollocks, bollox, 
	brotherfucker, bullshit, bumblefuck, buttfucka, buttfucker, carpetmuncher, chesticle, chinc, choad, chode, clitface, clitfuck, 
	clusterfuck, cockass, cockbite, cockburger, cockfucker, cockjockey, cockknoker, cockmaster, cockmongler, cockmongruel, cockmonkey, 
	cocknose, cocknugget, cockshit, cocksmith, cocksmoke, cocksmoker, cocksniffer, cockwaffle, coochie, coochy, cooter, cracker, 
	cumbubble, cumdumpster, cumguzzler, cumjockey, cumslut, cumtart, cunnie, cuntass, cuntface, cunthole, cuntrag, cuntslut, dago, deggo, 
	dickbag, dickbeaters, dickface, dickfuck, dickfucker, dickhole, dickjuice, dickmilk, dickmonger, dicks, dickslap, dicksucker, 
	dicksucking, dicktickler, dickwad, dickweasel, dickweed, dickwod, dike, dipshit, doochbag, dookie, douche, douchebag, douchewaffle, 
	dumass, dumbass, dumbfuck, dumbshit, dumshit, fagbag, fagfucker, faggit, faggotcock, fagtard, feltch, flamer, fuckass, fuckbag, 
	fuckboy, fuckbrain, fuckbutt, fuckbutter, fuckersucker, fuckface, fuckhole, fucknut, fucknutt, fuckoff, fuckstick, fucktard, fucktart, 
	fuckup, fuckwad, fuckwitt, gay, gayass, gaybob, gaydo, gayfuck, gayfuckist, gaytard, gaywad, goddamnit, gooch, gook, gringo, guido, 
	handjob, heeb, ho, hoe, homodumbshit, honkey, humping, jackass, jagoff, jerkass, jigaboo, junglebunny, kike, kooch, kootch, kraut, kunt, 
	kyke, lameass, lardass, lesbian, lesbo, lezzie, mcfagget, mick, minge, muffdiver, munging, negro, nigaboo, niglet, paki, panooch, 
	peckerhead, penisbanger, penispuffer, polesmoker, pollock, poon, poonani, poonany, poontang, porchmonkey, punanny, punta, pussylicking, 
	puto, queef, queer, queerbait, queerhole, renob, rimjob, ruski, sandnigger, shitass, shitbag, shitbagger, shitbrains, shitbreath, 
	shitcanned, shitcunt, shitface, shitfaced, shithole, shithouse, shitspitter, shitstain, shittiest, shiz, shiznit, skeet, skullfuck, 
	slutbag, smeg, spic, spick, splooge, spook, suckass, tard, thundercunt, twatlips, twats, twatwaffle, unclefucker, vag, vajayjay, 
	vjayjay, wankjob, wetback, whorebag, whoreface, wop, breeder, cocklump, creampie, doublelift, dumbcunt, incest,  poopuncher, sandler, 
	cockeye, crotte, foah, fucktwat, jaggi, kunja, pust, sanger, seks, slag, zubb, acrotomophilia, anilingus, apeshit, autoerotic, babeland, 
	bangbros, bareback, barenaked, bastardo, bastinado, bbw, bdsm, beaners, bimbos, birdlock, blumpkin, bondage, bukkake, bulldyke, bunghole, 
	busty, buttcheeks, camgirl, camslut, camwhore, circlejerk, coprolagnia, coprophilia, cornhole, coons, darkie, daterape, deepthroat, 
	dendrophilia, dingleberry, dingleberries, doggiestyle, doggystyle, dolcett, domination, dominatrix, dommes, dvda, ecchi, erotism, 
	escort, eunuch, fecal, felch,  femdom, figging, fingerbang, fingering, fisting, footjob, frotting, fucktards, futanari, genitals, goatcx, 
	gokkun, goodpoop, goregasm, grope, guro, hardcore, hentai, homoerotic, hooker, intercourse, jailbait, jiggaboo, jiggerboo, juggs,
	kinbaku, kinkster, kinky, knobbing, lolita, lovemaking, milf, muffdiving, nambla, nawashi, neonazi, nimphomania, nipple, nipples, nude,
	nudity, nympho, nymphomania, octopussy, omorashi, orgy, paedophile, panties, panty, pedobear, pedophile, pegging, pisspig, playboy,  
	ponyplay, poof, punany, poopchute, pthc, pubes, queaf, quim, raghead, raping, rapist, sadism, santorum, scat, scissoring, sexo, sexy, 
	shibari, shitblimp, shota, shrimping, slanteye, snowballing, sodomize, sodomy, spooge, strapon, strappado, suck, sucks, swastika, 
	swinger, threesome, throating, titty, topless, towelhead, tranny, tribadism, tubgirl, tushy, twink, twinkie, undressing, upskirt, 
	urophilia, vibrator, vorarephilia, voyeur,  xx, yaoi, yellow, yiffy, zoophilia
	}


